### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by maasencioh** [mljs/simple-clustering#3]
What it's the intention of this repo? If we're going to maintain this at least should have some description in the readme

cc @andcastillo @lpatiny

**Comment by maasencioh** [comment]
ping @andcastillo

**Comment by andcastillo** [comment]
job accepted.

**Comment by maasencioh** [comment]
![Challenge accepted](http://33.media.tumblr.com/aebeb686a640493b512c8999881d1fb5/tumblr_njzrzaICmG1s3h43ko1_500.gif)
